ingress:
  enabled: true
  className: traefik
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: ca-homelab
  hosts:
    - host: gitea.local-pi
      paths:
        - path: /
  tls:
    - secretName: gitea-tls
      hosts:
        - gitea.local-pi

valkey:
  enabled: true
valkey-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  create: true
  mount: true
  size: 256Mi

gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    security:
      ALLOWED_HOST_LIST: private

# Created with:
# kubectl create secret generic homelab-ca \
#  --from-file=homelab-ca.crt=./certs/ca.crt \
#  -n gitea
extraVolumes:
  - name: homelab-ca
    secret:
      secretName: homelab-ca

extraVolumeMounts:
  - name: homelab-ca
    mountPath: /usr/local/share/ca-certificates/homelab-ca.crt
    subPath: homelab-ca.crt
    readOnly: true